on: [push, pull_request]

name: CI

env:
    IMAGE_PARSER: ${{ secrets.DOCKER_HUB_ORGANIZATION }}/datelazi-parser
    IMAGE_API: ${{ secrets.DOCKER_HUB_ORGANIZATION }}/datelazi-api
    IMAGE_FRONTEND: ${{ secrets.DOCKER_HUB_ORGANIZATION }}/datelazi-frontend

jobs:
    build-parser:
        name: Build Parser container
        runs-on: ubuntu-latest

        steps:
            - name: Checkoout
              uses: actions/checkout@v1

            - name: Build Docker image
              id: build-parser
              run: |

                  docker build . \
                    --tag $IMAGE_PARSER:$GITHUB_SHA
            - name: Upload Docker image
              if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
              run: |
                  echo ${{ secrets.DOCKER_HUB_PASSWORD }} | \
                  docker login \
                    -u ${{ secrets.DOCKER_HUB_USERNAME }} \
                    --password-stdin
                  docker push $IMAGE_PARSER:$GITHUB_SHA
            - name: Tag Staging
              if: github.ref == 'refs/heads/develop'
              run: |
                  docker tag \
                    $IMAGE_PARSER:$GITHUB_SHA \
                    $IMAGE_PARSER:staging
                  docker push $IMAGE_PARSER:staging

            - name: Tag Latest
              if: github.ref == 'refs/heads/master'
              run: |
                  docker tag \
                    $IMAGE_PARSER:$GITHUB_SHA \
                    $IMAGE_PARSER:latest
                  docker push $IMAGE_PARSER:latest
